[package]
name = "clipboard-applet"
version = "0.1.0"
edition = "2024"

[dependencies]
ksni = "0.3.6"
libc = "0.2.189"
notify-rust = "4.18.0"
serde = { version = "1.0.229", features = ["derive"] }
tempfile = "3.27.0"
tokio = { version = "1", features = ["macros", "rt", "signal", "sync", "time"] }
toml = "1.1.4"
wayland-client = "0.31.15"
wayland-protocols = { version = "0.32.13", features = ["client", "staging"] }
wayland-protocols-wlr = { version = "0.3.12", features = ["client"] }
wl-clipboard-rs = "0.9.3"
